services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./server:/app
      - ./env:/env
    env_file:
      - ./env/.env.defaults  # Load non-sensitive environment variables
      - ./env/${NODE_ENV:-development}/.env.database  # Load non-sensitive environment variables
      - ./env/${NODE_ENV:-development}/.env.server  # Load non-sensitive environment variables
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: database
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - server_jwt_access_secret
      - server_jwt_refresh_secret
    depends_on:
      database:
        condition: service_healthy
    mem_limit: 512m
    networks:
      - app_network

  database:
    image: postgres:17-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password # Securely load password
      POSTGRES_DB: widenaturals_erp_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - app_network

volumes:
  pgdata:

secrets:
  server_jwt_access_secret:
    file: ./secrets/${NODE_ENV:-development}/server_jwt_access_secret.txt
  server_jwt_refresh_secret:
    file: ./secrets/${NODE_ENV:-development}/server_jwt_refresh_secret.txt
  db_password:
    file: ./secrets/${NODE_ENV:-development}/db_password.txt

networks:
  app_network:
    driver: bridge
