services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ./env:/env
    env_file:
      - ./env/.env.defaults  # Load non-sensitive environment variables
      - ./env/${NODE_ENV:-development}/.env.database  # Load non-sensitive environment variables
      - ./env/${NODE_ENV:-development}/.env.server  # Load non-sensitive environment variables
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - server_jwt_secret
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password # Securely load password
      POSTGRES_DB: widenaturals_erp_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:

secrets:
  server_jwt_secret:
    file: ./secrets/${NODE_ENV:-development}/server_jwt_secret.txt
  db_password:
    file: ./secrets/${NODE_ENV:-development}/db_password.txt
