import type {
  NullableNumber,
  NullableString
} from '@shared-types/shared';
import type {
  ApiSuccessResponse,
  AsyncState,
  OperationStats,
} from '@shared-types/api';

/**
 * Input payload for creating a single product.
 *
 * Represents one row in a bulk product creation request.
 * Mirrors backend validation rules (Joi schema).
 *
 * Fields such as `series`, `description`, and dimensions are optional
 * and may be `null` when omitted.
 *
 * @example
 * const product: CreateProductInput = {
 *   name: "Omega-3 Softgels",
 *   brand: "Wide Naturals",
 *   category: "Supplements",
 *   series: null,
 *   weight_g: 150
 * };
 */
export interface CreateProductInput {
  /** Product name — required (2–255 chars). */
  name: string;
  
  /** Optional product series or line (nullable). */
  series?: NullableString;
  
  /** Brand name — required and validated via BRAND_CATEGORY_REGEX. */
  brand: string;
  
  /** Category name — required and validated via BRAND_CATEGORY_REGEX. */
  category: string;
  
  /** Optional long description (nullable, up to 1000 chars). */
  description?: NullableString;
  
  /** Optional product length in centimeters (positive number or null). */
  length_cm?: NullableNumber;
  
  /** Optional product width in centimeters (positive number or null). */
  width_cm?: NullableNumber;
  
  /** Optional product height in centimeters (positive number or null). */
  height_cm?: NullableNumber;
  
  /** Optional product weight in grams (positive number or null). */
  weight_g?: NullableNumber;
}

/**
 * Bulk request payload for creating one or more products.
 *
 * This is the object passed directly into the API endpoint or thunk.
 *
 * @example
 * const payload: CreateProductBulkInput = {
 *   products: [
 *     { name: "Fish Oil", brand: "WN", category: "Health" },
 *     { name: "Vitamin D", brand: "WN", category: "Health" }
 *   ]
 * };
 */
export interface CreateProductBulkInput {
  /** Array of product definitions to create in a single operation. */
  products: CreateProductInput[];
}

/**
 * Represents a product record returned from the backend
 * after a successful create operation.
 *
 * Includes the autogenerated UUID but excludes all other fields
 * for performance and simplicity.
 *
 * @example
 * { id: "e030af90-2417-4ef4-9135-8495b80a3ace" }
 */
export interface CreatedProduct {
  /** Auto-generated unique identifier (UUID). */
  id: string;
}

/**
 * API response type returned from the backend when creating products.
 *
 * Extends `ApiSuccessResponse` to include:
 *  - `data`: an array of created product records
 *  - `stats`: operational metadata such as inputCount, processedCount, elapsedMs
 *
 * @example
 * const res: CreateProductResponse = {
 *   success: true,
 *   message: "Products created successfully",
 *   data: [{ id: "uuid-1" }, { id: "uuid-2" }],
 *   stats: { inputCount: 2, processedCount: 2, elapsedMs: 4 }
 * };
 */
export interface CreateProductResponse
  extends ApiSuccessResponse<CreatedProduct[]> {
  /** Operational statistics about the bulk creation operation. */
  stats: OperationStats;
}

/**
 * Redux state shape for the create-products async operation.
 *
 * Wraps the API response in a generic AsyncState<T> structure, giving:
 *  - `data`: the API response or null
 *  - `loading`: boolean flag
 *  - `error`: string or null
 *
 * @example
 * const state: CreateProductsState = {
 *   data: null,
 *   loading: false,
 *   error: null
 * };
 */
export type CreateProductsState = AsyncState<CreateProductResponse | null>;
