import type {
  NullableString
} from '@shared-types/shared';
import type {
  ApiSuccessResponse,
  AsyncState,
  GenericAudit,
  GenericStatus,
  OperationStats,
  PaginatedResponse,
  PaginationParams,
  ReduxPaginatedState,
  SortConfig,
} from '@shared-types/api';

/**
 * Input payload for creating a single product.
 *
 * Represents one row in a bulk product creation request.
 * Mirrors backend validation rules (Joi schema).
 *
 * Fields such as `series`, `description`, and dimensions are optional
 * and may be `null` when omitted.
 *
 * @example
 * const product: CreateProductInput = {
 *   name: "Omega-3 Softgels",
 *   brand: "Wide Naturals",
 *   category: "Supplements",
 *   series: null,
 *   weight_g: 150
 * };
 */
export interface CreateProductInput {
  /** Product name — required (2–255 chars). */
  name: string;
  
  /** Optional product series or line (nullable). */
  series?: NullableString;
  
  /** Brand name — required and validated via BRAND_CATEGORY_REGEX. */
  brand: string;
  
  /** Category name — required and validated via BRAND_CATEGORY_REGEX. */
  category: string;
  
  /** Optional long description (nullable, up to 1000 chars). */
  description?: NullableString;
}

/**
 * Bulk request payload for creating one or more products.
 *
 * This is the object passed directly into the API endpoint or thunk.
 *
 * @example
 * const payload: CreateProductBulkInput = {
 *   products: [
 *     { name: "Fish Oil", brand: "WN", category: "Health" },
 *     { name: "Vitamin D", brand: "WN", category: "Health" }
 *   ]
 * };
 */
export interface CreateProductBulkInput {
  /** Array of product definitions to create in a single operation. */
  products: CreateProductInput[];
}

/**
 * Represents a product record returned from the backend
 * after a successful create operation.
 *
 * Includes the autogenerated UUID but excludes all other fields
 * for performance and simplicity.
 *
 * @example
 * { id: "e030af90-2417-4ef4-9135-8495b80a3ace" }
 */
export interface CreatedProduct {
  /** Auto-generated unique identifier (UUID). */
  id: string;
}

/**
 * API response type returned from the backend when creating products.
 *
 * Extends `ApiSuccessResponse` to include:
 *  - `data`: an array of created product records
 *  - `stats`: operational metadata such as inputCount, processedCount, elapsedMs
 *
 * @example
 * const res: CreateProductResponse = {
 *   success: true,
 *   message: "Products created successfully",
 *   data: [{ id: "uuid-1" }, { id: "uuid-2" }],
 *   stats: { inputCount: 2, processedCount: 2, elapsedMs: 4 }
 * };
 */
export interface CreateProductResponse
  extends ApiSuccessResponse<CreatedProduct[]> {
  /** Operational statistics about the bulk creation operation. */
  stats: OperationStats;
}

/**
 * Redux state shape for the create-products async operation.
 *
 * Wraps the API response in a generic AsyncState<T> structure, giving:
 *  - `data`: the API response or null
 *  - `loading`: boolean flag
 *  - `error`: string or null
 *
 * @example
 * const state: CreateProductsState = {
 *   data: null,
 *   loading: false,
 *   error: null
 * };
 */
export type CreateProductsState = AsyncState<CreateProductResponse | null>;

/**
 * Represents a single product entry returned in a paginated product list.
 *
 * Includes product identity, classification details, current status,
 * and audit metadata (created/updated timestamps).
 */
export interface ProductListItem {
  /** Unique product identifier (UUID) */
  id: string;
  
  /** Product name */
  name: string;
  
  /** Product series label (may be null if unset) */
  series: NullableString;
  
  /** Product brand (maybe null if unset) */
  brand: NullableString;
  
  /** Product category (maybe null if unset) */
  category: NullableString;
  
  /** Product status object including name, id, and date */
  status: GenericStatus;
  
  /** Audit information including created and updated timestamps */
  audit: GenericAudit;
}

/**
 * Standard paginated API response structure for product lists.
 *
 * Wraps:
 * - product list items
 * - success flag
 * - message
 * - pagination metadata
 */
export type ProductListResponse = PaginatedResponse<ProductListItem>;

/**
 * Supported filter options for fetching paginated product lists.
 *
 * All values are optional; undefined values are excluded from the query string.
 * This object is flattened into URL query params by the fetch helper.
 */
export interface ProductListFilters {
  /** Optional product status filter (UUID or multiple UUIDs) */
  statusIds?: string | string[];
  
  /** Optional brand search (partial match allowed) */
  brand?: string;
  
  /** Optional category search (partial match allowed) */
  category?: string;
  
  /** Optional series search (partial match allowed) */
  series?: string;
  
  /** Filter by creator user ID */
  createdBy?: string;
  
  /** Filter by last-updater user ID */
  updatedBy?: string;
  
  /** Keyword-based fuzzy text search across name, brand, category, status */
  keyword?: string;
}

/**
 * Allowed sortable fields for product list queries.
 *
 * These map directly to SQL columns via `productSortMap` on the backend.
 */
export type ProductSortField =
  | 'productName'
  | 'series'
  | 'brand'
  | 'category'
  | 'description'
  | 'statusName'
  | 'statusId'
  | 'statusDate'
  | 'createdAt'
  | 'updatedAt'
  | 'createdByFirstName'
  | 'createdByLastName'
  | 'updatedByFirstName'
  | 'updatedByLastName'
  | 'defaultNaturalSort';

/**
 * Query parameters accepted by the product list fetcher.
 *
 * Combines:
 * - Pagination (page, limit)
 * - Sort configuration (sortBy, sortOrder)
 * - Structured filter object
 */
export interface FetchProductParams extends PaginationParams, SortConfig {
  /** Optional structured filter object merged into the query string */
  filters?: ProductListFilters;
}

/**
 * Redux slice state for paginated product lists.
 *
 * Generated via a reusable `ReduxPaginatedState<T>` helper and includes:
 * - data (product list items)
 * - pagination metadata
 * - loading flag
 * - error message (if any)
 */
export type ProductListState = ReduxPaginatedState<ProductListItem>;

/**
 * Represents a normalized, table-friendly version of a product record.
 *
 * This structure is produced by `flattenProductRecords()` and provides
 * a clean flat shape optimized for rendering in product list tables,
 * expandable rows, and data grids. It removes nested objects from the
 * API response and standardizes missing or null fields.
 *
 * Includes:
 * - Core product identity fields
 * - Status metadata
 * - Audit trail information
 *
 * All fields are formatted as simple strings to ensure predictable UI rendering.
 */
export interface FlattenedProductRecord {
  /** Unique product identifier */
  productId: string;
  
  /** Product name */
  name: string;
  
  /** Product brand label */
  brand: string;
  
  /** Product series label */
  series: string;
  
  /** Product category label */
  category: string;
  
  // -----------------------------
  // Status Information
  // -----------------------------
  
  /** Human-readable status name (e.g., "active", "inactive") */
  statusName: string;
  
  /** ISO timestamp representing when the status was last updated */
  statusDate: string;
  
  // -----------------------------
  // Audit Information
  // -----------------------------
  
  /** ISO timestamp representing when the product was created */
  createdAt: string;
  
  /** Name of the user who created the product */
  createdBy: string;
  
  /** ISO timestamp of last update (may be null if never updated) */
  updatedAt: NullableString;
  
  /** Name of the user who last updated the product (nullable) */
  updatedBy: NullableString;
}
