export const API_ENDPOINTS = {
  CSRF_TOKEN: '/csrf/token',
  USER_PERMISSION: '/users/me/permissions',
  PUBLIC_HEALTH: '/public/health',
  LOGIN: '/session/login',
  RESET_PASSWORD: '/auth/reset-password',
  REFRESH_TOKEN: '/session/refresh',
  LOGOUT: '/auth/logout',
  ALL_USERS: '/users',
  USER_PROFILE: '/users/me',
  PRODUCTS_DROPDOWN_WAREHOUSE: '/products/dropdown/warehouse/:warehouseId',
  ACTIVE_SKU_PRODUCT_CARDS: '/skus/cards/active',
  SKU_DETAILS: '/skus/sku-details/:skuId',
  ALL_COMPLIANCES: '/compliances',
  PRICING_TYPES: '/pricing-types',
  PRICING_TYPE_METADATA: '/pricing-types/metadata/:id',
  PRICING_LIST: '/pricings',
  PRICING_LIST_EXPORT: '/pricings/export',
  PRICING_DETAILS_BY_TYPE: '/pricings/by-type/:id/details',
  ALL_LOCATION_TYPES: '/location-types',
  LOCATION_TYPE_DETAILS: '/location-types/:id',
  ALL_LOCATIONS: '/locations',
  LOCATION_INVENTORY: {
    KPI_SUMMARY: '/location-inventory/kpi-summary',
    SUMMARY: '/location-inventory/summary',
    SUMMARY_DETAIL: (itemId: string) =>
      `/location-inventory/summary/${itemId}/details`,
  },
  ALL_WAREHOUSES: '/warehouses',
  WAREHOUSE_DETAILS: '/warehouses/details/:id',
  WAREHOUSES_DROPDOWN: '/warehouses/dropdown',
  WAREHOUSE_INVENTORIES_SUMMARY: '/warehouses/inventory-overview',
  ALL_WAREHOUSE_INVENTORIES: '/warehouse-inventory',
  WAREHOUSE_INVENTORY_SUMMARY: '/warehouse-inventory/summary',
  WAREHOUSE_INVENTORY_SUMMARY_DETAIL: '/warehouse-inventory/summary/:itemId/details',
  WAREHOUSE_ITEMS_SUMMARY: '/warehouse-inventory/:id/items-summary',
  WAREHOUSE_INVENTORY_DETAILS: '/warehouse-inventory/:id',
  LOT_ADJUSTMENT_TYPES_DROPDOWN: '/lot-adjustment-types/dropdown',
  WAREHOUSE_INVENTORY_LOT_SINGLE_ADJUST: '/warehouse-inventory-lots/adjust/:id',
  WAREHOUSE_INVENTORY_LOT_BULK_ADJUST: '/warehouse-inventory-lots/adjust/bulk',
  WAREHOUSE_INVENTORY_BULK_INSERT: '/inventories/add-inventory-records',
  WAREHOUSE_INVENTORY_LOT_INSERT_RESPONSE:
    '/warehouse-inventory-lots/inventory-records/recent-inserts',
  WAREHOUSE_INVENTORY_LOT_INVENTORY_AVAILABLE: '/warehouse-inventory-lots/inventory/:inventoryId/lots',
  WAREHOUSE_INVENTORY_ADJUSTMENTS_REPORT: '/reports/adjustments',
  WAREHOUSE_INVENTORY_ACTIVITY_LOGS: '/reports/inventory-activity-logs',
  INVENTORY_HISTORY: '/reports/inventory-history',
  ALL_ORDER_TYPES: '/order-types',
  ORDER_TYPES_DROPDOWN: '/order-types/dropdown',
  ADD_NEW_CUSTOMER: '/customers/add-new-customer',
  ADD_NEW_CUSTOMERS_BULK: '/customers/bulk/add-new-customers',
  ALL_CUSTOMERS: '/customers',
  CUSTOMER_DETAILS: '/customers/:id',
  CUSTOMERS_DROPDOWN: '/customers/dropdown',
  ALL_ORDERS: '/orders',
  ALLOCATION_ELIGIBLE_ORDERS: '/orders/allocation-eligible',
  CREATE_SALES_ORDERS: '/orders/order-types/:orderTypeId',
  CONFIRM_SALES_ORDER: '/orders/:orderId/confirm',
  DISCOUNTS_DROPDOWN: '/discounts/dropdown',
  TAX_RATES_DROPDOWN: '/tax-rates/dropdown',
  DELIVERY_METHODS_DROPDOWN: '/delivery-methods/dropdown',
  PRODUCTS_DROPDOWN_ORDERS: '/products/dropdown/orders',
  PRICING_TYPES_DROPDOWN: '/pricing-types/dropdown',
  PRICE_VALUE: '/pricings/fetch-price',
  SALES_ORDER_DETAILS: '/orders/sales-order/details/:id',
  ALLOCATION_ELIGIBLE_ORDER_DETAILS: '/orders/:id/allocation',
  INVENTORY_ALLOCATION_EXECUTE: '/inventory-allocation/allocate/:id',
};
