export const API_ENDPOINTS = {
  CSRF_TOKEN: '/csrf/token',
  USER_PERMISSION: '/users/me/permissions',
  PUBLIC_HEALTH: '/public/health',
  LOGIN: '/session/login',
  RESET_PASSWORD: '/auth/reset-password',
  REFRESH_TOKEN: '/session/refresh',
  LOGOUT: '/auth/logout',
  ALL_USERS: '/users',
  USER_PROFILE: '/users/me',
  PRODUCTS_DROPDOWN_WAREHOUSE: '/products/dropdown/warehouse/:warehouseId',
  ACTIVE_SKU_PRODUCT_CARDS: '/skus/cards/active',
  SKU_DETAILS: '/skus/sku-details/:skuId',
  ALL_COMPLIANCES: '/compliances',
  PRICING_TYPES: '/pricing-types',
  PRICING_TYPE_METADATA: '/pricing-types/metadata/:id',
  PRICING_LIST: '/pricings',
  PRICING_LIST_EXPORT: '/pricings/export',
  PRICING_DETAILS_BY_TYPE: '/pricings/by-type/:id/details',
  ALL_LOCATION_TYPES: '/location-types',
  LOCATION_TYPE_DETAILS: '/location-types/:id',
  ALL_LOCATIONS: '/locations',
  LOCATION_INVENTORY: {
    ALL_RECORDS: '/location-inventory',
    KPI_SUMMARY: '/location-inventory/kpi-summary',
    SUMMARY: '/location-inventory/summary',
    SUMMARY_DETAIL: (itemId: string) =>
      `/location-inventory/summary/${itemId}/details`,
  },
  ALL_WAREHOUSES: '/warehouses',
  WAREHOUSE_DETAILS: '/warehouses/details/:id',
  WAREHOUSE_INVENTORY: {
    ALL_RECORDS: '/warehouse-inventory',
    SUMMARY: '/warehouse-inventory/summary',
    SUMMARY_DETAIL: (itemId: string) =>
      `/warehouse-inventory/summary/${itemId}/details`,
    ADD_RECORDS: '/warehouse-inventory',
    ADJUST_QUANTITIES: '/warehouse-inventory/adjust-quantities',
  },
  LOOKUP: {
    BATCH_REGISTRY: '/lookups/batch-registry',
    WAREHOUSES: '/lookups/warehouses',
    LOT_ADJUSTMENT_TYPES: '/lookups/lot-adjustment-types',
  },
  REPORTS: {
    INVENTORY_ACTIVITY_LOGS: 'reports/inventory-activity-logs',
  },
  ALL_ORDER_TYPES: '/order-types',
  ORDER_TYPES_DROPDOWN: '/order-types/dropdown',
  CUSTOMERS: {
    ADD_NEW_CUSTOMERS: '/customers/add-new-customers',
    ALL_CUSTOMERS: '/customers',
    CUSTOMER_DETAILS: '/customers/:id',
  },
  ADDRESSES: {
    ADD_NEW_ADDRESSES: '/addresses/add-new-addresses',
  },
  ALL_ORDERS: '/orders',
  ALLOCATION_ELIGIBLE_ORDERS: '/orders/allocation-eligible',
  CREATE_SALES_ORDERS: '/orders/order-types/:orderTypeId',
  CONFIRM_SALES_ORDER: '/orders/:orderId/confirm',
  DISCOUNTS_DROPDOWN: '/discounts/dropdown',
  TAX_RATES_DROPDOWN: '/tax-rates/dropdown',
  DELIVERY_METHODS_DROPDOWN: '/delivery-methods/dropdown',
  PRODUCTS_DROPDOWN_ORDERS: '/products/dropdown/orders',
  PRICING_TYPES_DROPDOWN: '/pricing-types/dropdown',
  PRICE_VALUE: '/pricings/fetch-price',
  SALES_ORDER_DETAILS: '/orders/sales-order/details/:id',
  ALLOCATION_ELIGIBLE_ORDER_DETAILS: '/orders/:id/allocation',
  INVENTORY_ALLOCATION_EXECUTE: '/inventory-allocation/allocate/:id',
};
