export const API_ENDPOINTS = {
  CSRF_TOKEN: '/csrf/token',
  USER_PERMISSION: '/users/me/permissions',
  PUBLIC_HEALTH: '/public/health',
  LOGIN: '/session/login',
  RESET_PASSWORD: '/auth/reset-password',
  REFRESH_TOKEN: '/session/refresh',
  LOGOUT: '/auth/logout',
  ALL_USERS: '/users',
  USER_PROFILE: '/users/me',
  ALL_PRODUCTS: '/products',
  PRODUCT_DETAILS: '/products/product-details/:id',
  PRODUCTS_DROPDOWN: '/products/dropdown',
  ALL_PRICING_TYPES: '/pricing-types',
  PRICING_TYPE_DETAILS: '/pricing-types/:id',
  ALL_PRICINGS: '/pricings',
  PRICING_DETAILS: '/pricings/:id',
  ALL_LOCATION_TYPES: '/location-types',
  LOCATION_TYPE_DETAILS: '/location-types/:id',
  ALL_LOCATIONS: '/locations',
  ALL_INVENTORIES: '/inventories',
  ALL_WAREHOUSES: '/warehouses',
  WAREHOUSE_DETAILS: '/warehouses/details/:id',
  WAREHOUSES_DROPDOWN: '/warehouses/dropdown',
  WAREHOUSE_INVENTORIES_SUMMARY: '/warehouses/inventory-overview',
  ALL_WAREHOUSE_INVENTORIES: '/warehouse-inventories',
  WAREHOUSE_PRODUCTS_SUMMARY: '/warehouse-inventories/:id/products-summary',
  WAREHOUSE_INVENTORY_DETAILS: '/warehouse-inventories/:id',
  LOT_ADJUSTMENT_TYPES_DROPDOWN: '/lot-adjustment-types/dropdown',
  WAREHOUSE_INVENTORY_LOT_SINGLE_ADJUST: '/warehouse-inventory-lots/adjust/:id',
  WAREHOUSE_INVENTORY_LOT_BULK_ADJUST: '/warehouse-inventory-lots/adjust/bulk',
  WAREHOUSE_INVENTORY_BULK_INSERT: '/inventories/add-inventory-records',
  WAREHOUSE_INVENTORY_LOT_INSERT_RESPONSE:
    '/warehouse-inventory-lots/inventory-records/recent-inserts',
  WAREHOUSE_INVENTORY_ADJUSTMENTS_REPORT: '/reports/adjustments',
};
