export const API_ENDPOINTS = {
  CSRF_TOKEN: '/csrf/token',
  USER_PERMISSION: '/users/me/permissions',
  PUBLIC_HEALTH: '/public/health',
  LOGIN: '/session/login',
  RESET_PASSWORD: '/auth/reset-password',
  REFRESH_TOKEN: '/session/refresh',
  LOGOUT: '/auth/logout',
  ALL_USERS: '/users',
  USER_PROFILE: '/users/me',
  PRODUCTS_DROPDOWN_WAREHOUSE: '/products/dropdown/warehouse/:warehouseId',
  ACTIVE_SKU_PRODUCT_CARDS: '/skus/cards/active',
  SKU_DETAILS: '/skus/sku-details/:skuId',
  ALL_COMPLIANCES: '/compliances',
  PRICING_TYPES: '/pricing-types',
  PRICING_TYPE_METADATA: '/pricing-types/metadata/:id',
  PRICING_LIST: '/pricings',
  PRICING_LIST_EXPORT: '/pricings/export',
  PRICING_DETAILS_BY_TYPE: '/pricings/by-type/:id/details',
  ALL_LOCATION_TYPES: '/location-types',
  LOCATION_TYPE_DETAILS: '/location-types/:id',
  ALL_LOCATIONS: '/locations',
  LOCATION_INVENTORY: {
    ALL_RECORDS: '/location-inventory',
    KPI_SUMMARY: '/location-inventory/kpi-summary',
    SUMMARY: '/location-inventory/summary',
    SUMMARY_DETAIL: (itemId: string) =>
      `/location-inventory/summary/${itemId}/details`,
  },
  ALL_WAREHOUSES: '/warehouses',
  WAREHOUSE_DETAILS: '/warehouses/details/:id',
  WAREHOUSE_INVENTORY: {
    ALL_RECORDS: '/warehouse-inventory',
    SUMMARY: '/warehouse-inventory/summary',
    SUMMARY_DETAIL: (itemId: string) =>
      `/warehouse-inventory/summary/${itemId}/details`,
    ADD_RECORDS: '/warehouse-inventory',
    ADJUST_QUANTITIES: '/warehouse-inventory/adjust-quantities',
  },
  LOOKUPS: {
    BATCH_REGISTRY: '/lookups/batch-registry',
    WAREHOUSES: '/lookups/warehouses',
    LOT_ADJUSTMENT_TYPES: '/lookups/lot-adjustment-types',
    CUSTOMERS: '/lookups/customers',
    ADDRESSES_BY_CUSTOMER: '/lookups/addresses/by-customer',
    ORDER_TYPES: '/lookups/order-types',
    PAYMENT_METHODS: '/lookups/payment-methods',
    DISCOUNTS: '/lookups/discounts',
    TAX_RATES: '/lookups/tax-rates',
    DELIVERY_METHODS: '/lookups/delivery-methods',
    SKUS: '/lookups/skus',
    PRICING: '/lookups/pricing',
    PACKAGING_MATERIALS: '/lookups/packaging-materials',
  },
  REPORTS: {
    INVENTORY_ACTIVITY_LOGS: 'reports/inventory-activity-logs',
  },
  ORDER_TYPES: {
    ALL_RECORDS: '/order-types',
  },
  CUSTOMERS: {
    ADD_NEW_CUSTOMERS: '/customers/add-new-customers',
    ALL_CUSTOMERS: '/customers',
    CUSTOMER_DETAILS: '/customers/:id',
  },
  ADDRESSES: {
    ADD_NEW_ADDRESSES: '/addresses/add-new-addresses',
    ALL_RECORDS: '/addresses',
  },
  ORDERS: {
    ADD_NEW_ORDER: (category: string) => `/orders/create/${category}`,
    ORDER_DETAILS: (orderId: string) => `/orders/${orderId}`,
  },
};
