const { fetchDynamicValue } = require('../03_utils');

/**
 * @param { import("knex").Knex } knex
 * @returns {Promise<void>}
 */
exports.seed = async function (knex) {
  const activeStatusId = await fetchDynamicValue(
    knex,
    'status',
    'name',
    'active',
    'id'
  );
  const pendingStatusId = await fetchDynamicValue(
    knex,
    'status',
    'name',
    'pending',
    'id'
  );
  const inactiveStatusId = await fetchDynamicValue(
    knex,
    'status',
    'name',
    'inactive',
    'id'
  );
  const adminUserId = await fetchDynamicValue(
    knex,
    'users',
    'email',
    'admin@example.com',
    'id'
  );

  const products = [
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Eco-Friendly Water Bottle',
      series: 'Hydration Plus',
      brand: 'EcoLife',
      category: 'Drinkware',
      SKU: 'ECO-WTR-001',
      barcode: '1234567890123',
      market_region: 'North America',
      length_cm: 25.0,
      width_cm: 8.0,
      height_cm: 8.0,
      weight_g: 500.0,
      description:
        'A reusable water bottle made from BPA-free materials, perfect for daily hydration.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Organic Cotton Tote Bag',
      series: 'Nature Carry',
      brand: 'EcoLife',
      category: 'Accessories',
      SKU: 'ECO-BAG-002',
      barcode: '1234567890456',
      market_region: 'Europe',
      length_cm: 40.0,
      width_cm: 10.0,
      height_cm: 35.0,
      weight_g: 300.0,
      description:
        'A durable tote bag made from 100% organic cotton, ideal for groceries and daily errands.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Biodegradable Phone Case',
      series: 'EcoCover',
      brand: 'GreenTech',
      category: 'Electronics',
      SKU: 'GTC-CASE-003',
      barcode: '1234567890789',
      market_region: 'Asia',
      length_cm: 15.0,
      width_cm: 7.0,
      height_cm: 1.0,
      weight_g: 100.0,
      description:
        'An eco-friendly phone case made from biodegradable materials, stylish and sustainable.',
      status_id: inactiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Solar-Powered Backpack',
      series: 'SunCharger',
      brand: 'GreenTech',
      category: 'Accessories',
      SKU: 'GTC-BACK-004',
      barcode: '1234567890987',
      market_region: 'Global',
      length_cm: 50.0,
      width_cm: 20.0,
      height_cm: 30.0,
      weight_g: 1200.0,
      description:
        'A versatile backpack with solar panels to charge your devices on the go.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Bamboo Cutlery Set',
      series: 'EcoDine',
      brand: 'EcoLife',
      category: 'Kitchenware',
      SKU: 'ECO-CUT-005',
      barcode: '1234567890654',
      market_region: 'Australia',
      length_cm: 10.0,
      width_cm: 5.0,
      height_cm: 2.0,
      weight_g: 200.0,
      description:
        'A compact, reusable cutlery set made from sustainable bamboo.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Recycled Notebook',
      series: 'Paper Saver',
      brand: 'EcoLife',
      category: 'Stationery',
      SKU: 'ECO-NB-006',
      barcode: '1234567890999',
      market_region: 'South America',
      length_cm: 25.0,
      width_cm: 18.0,
      height_cm: 2.0,
      weight_g: 400.0,
      description: 'A notebook made from 100% recycled paper.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Organic Facial Wipes',
      series: 'SkinCare+',
      brand: 'GreenBeauty',
      category: 'Personal Care',
      SKU: 'GB-FW-007',
      barcode: '1234567890543',
      market_region: 'Middle East',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      description: 'Gentle and organic facial wipes for all skin types.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Compostable Trash Bags',
      series: 'GreenBin',
      brand: 'EcoLife',
      category: 'Household',
      SKU: 'ECO-TB-008',
      barcode: '1234567890234',
      market_region: 'Global',
      length_cm: 45.0,
      width_cm: 40.0,
      height_cm: 2.0,
      weight_g: 1500.0,
      description: 'Durable trash bags that are fully compostable.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Reusable Silicone Food Bags',
      series: 'EcoSeal',
      brand: 'EcoLife',
      category: 'Kitchenware',
      SKU: 'ECO-BAG-009',
      barcode: '1234567891123',
      market_region: 'Global',
      length_cm: 25.0,
      width_cm: 20.0,
      height_cm: 2.0,
      weight_g: 200.0,
      description:
        'A set of reusable, eco-friendly silicone food bags for storage.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Natural Wool Dryer Balls',
      series: 'EcoDry',
      brand: 'EcoLife',
      category: 'Laundry',
      SKU: 'ECO-DRY-010',
      barcode: '1234567891456',
      market_region: 'North America',
      length_cm: 6.0,
      width_cm: 6.0,
      height_cm: 6.0,
      weight_g: 300.0,
      description:
        'A pack of natural wool dryer balls for a sustainable laundry experience.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Compostable Coffee Pods',
      series: 'EcoBrew',
      brand: 'GreenBeans',
      category: 'Food & Beverage',
      SKU: 'GB-COFFEE-011',
      barcode: '1234567891789',
      market_region: 'Europe',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 10.0,
      weight_g: 800.0,
      description:
        'Compostable coffee pods compatible with popular coffee machines.',
      status_id: pendingStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Recycled Glass Water Bottle',
      series: 'EcoSip',
      brand: 'EcoLife',
      category: 'Drinkware',
      SKU: 'ECO-BTL-012',
      barcode: '1234567891987',
      market_region: 'Asia',
      length_cm: 22.0,
      width_cm: 7.0,
      height_cm: 7.0,
      weight_g: 550.0,
      description:
        'A reusable glass water bottle made from recycled materials.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Bamboo Toothbrush',
      series: 'EcoSmile',
      brand: 'GreenBeauty',
      category: 'Personal Care',
      SKU: 'GB-TOOTH-013',
      barcode: '1234567892123',
      market_region: 'Global',
      length_cm: 19.0,
      width_cm: 2.0,
      height_cm: 1.5,
      weight_g: 30.0,
      description: 'A biodegradable bamboo toothbrush for a greener smile.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Eco-Friendly Yoga Mat',
      series: 'EcoStretch',
      brand: 'GreenFitness',
      category: 'Fitness',
      SKU: 'GF-YOGA-014',
      barcode: '1234567892345',
      market_region: 'Global',
      length_cm: 180.0,
      width_cm: 60.0,
      height_cm: 0.5,
      weight_g: 1200.0,
      description:
        'A non-toxic, eco-friendly yoga mat for sustainable workouts.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Reusable Makeup Remover Pads',
      series: 'EcoClean',
      brand: 'GreenBeauty',
      category: 'Personal Care',
      SKU: 'GB-MR-015',
      barcode: '1234567892678',
      market_region: 'North America',
      length_cm: 10.0,
      width_cm: 10.0,
      height_cm: 1.0,
      weight_g: 100.0,
      description:
        'Soft and reusable makeup remover pads made from organic cotton.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Solar LED String Lights',
      series: 'EcoGlow',
      brand: 'GreenTech',
      category: 'Home Decor',
      SKU: 'GT-LIGHTS-016',
      barcode: '1234567892789',
      market_region: 'Global',
      length_cm: 500.0,
      width_cm: 0.5,
      height_cm: 0.5,
      weight_g: 800.0,
      description:
        'Solar-powered LED string lights for eco-friendly home decor.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Compostable Plant Pots',
      series: 'EcoPlanter',
      brand: 'GreenGardens',
      category: 'Gardening',
      SKU: 'GG-POT-017',
      barcode: '1234567892987',
      market_region: 'Europe',
      length_cm: 12.0,
      width_cm: 12.0,
      height_cm: 12.0,
      weight_g: 200.0,
      description: 'Compostable plant pots for sustainable gardening.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Biodegradable Food Wrap',
      series: 'EcoWrap',
      brand: 'EcoLife',
      category: 'Kitchenware',
      SKU: 'ECO-WRAP-018',
      barcode: '1234567893234',
      market_region: 'Australia',
      length_cm: 30.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 500.0,
      description: 'A biodegradable food wrap for a zero-waste kitchen.',
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      created_by: adminUserId,
      updated_by: adminUserId,
    },
  ];

  let successCount = 0;

  // Insert data with ON CONFLICT to avoid duplicates
  for (const product of products) {
    try {
      await knex('products')
        .insert(product)
        .onConflict('SKU') // Specify the column with the unique constraint
        .ignore(); // Ignore if the SKU already exists
      successCount++;
    } catch (error) {
      console.error('Error seeding product:', product.SKU, error.message);
    }
  }

  console.log(`${successCount} Products seeded successfully.`);
};
