const { fetchDynamicValue } = require('../03_utils');

/**
 * @param { import("knex").Knex } knex
 * @returns {Promise<void>}
 */
exports.seed = async function (knex) {
  const activeStatusId = await fetchDynamicValue(
    knex,
    'status',
    'name',
    'active',
    'id'
  );
  const inActiveStatusId = await fetchDynamicValue(
    knex,
    'status',
    'name',
    'inactive',
    'id'
  );
  const discontinuedStatusId = await fetchDynamicValue(
    knex,
    'status',
    'name',
    'discontinued',
    'id'
  );
  const systemActionId = await fetchDynamicValue(
    knex,
    'users',
    'email',
    'system@internal.local',
    'id'
  );

  const products = [
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Focus - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN101-R-INT', // Corrected SKU
      barcode: '628942007071', // Actual barcode
      market_region: 'International', // Canada
      description: '改善大脑功能，提升精神集中和精神耐力',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Gut Health - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN102-R-INT',
      barcode: '628942007088',
      market_region: 'International',
      description: '有效改善消化功能，刺激食欲',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Immune - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN103-R-INT',
      barcode: '628942007101',
      market_region: 'International',
      description: '提升自然免疫系统',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Memory - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN104-R-INT',
      barcode: '628942007057',
      market_region: 'International',
      description: '改善记忆、认知健康、大脑功能',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Menopause - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN105-R-INT',
      barcode: '628942007095',
      market_region: 'International',
      description: '缓解更年期相关症状',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Mood - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN106-R-INT',
      barcode: '628942007064',
      market_region: 'International',
      description: '有助于维持健康稳定的情绪',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Sleep - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN107-R-INT',
      barcode: '628942007040',
      market_region: 'International',
      description: '提升睡眠质量，缓解紧张情绪',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Pain Relief - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN108-R-INT',
      barcode: '628942007125',
      market_region: 'International',
      description: '超浓缩、快速吸收，舒缓肌肉酸痛等各类疼痛',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: discontinuedStatusId, // Out of Stock
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Hair Health - INT',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN109-R-INT',
      barcode: '000000000000',
      market_region: 'International',
      description: '恢复靓丽秀发 保持发肤健康',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: discontinuedStatusId, // Out of Stock
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Focus - CA',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN101-R-CA', // Corrected SKU
      barcode: '628693253062', // Actual barcode
      market_region: 'Canada', // Canada
      description: 'Improve Mental Performance',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Gut Health - CA',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN102-R-CA',
      barcode: '628693253055',
      market_region: 'Canada',
      description: 'Treats Digestive Upset',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Immune - CA',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN103-R-CA',
      barcode: '628693253017',
      market_region: 'Canada',
      description: 'Maintains a Healthy Immune System',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Memory - CA',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN104-R-CA',
      barcode: '628693253031',
      market_region: 'Canada',
      description: 'Support Memory & Cognitive Health',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Menopause - CA',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN110-R-CA',
      barcode: '628693253048',
      market_region: 'Canada',
      description: 'Relieves Symptoms of Menopause',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Mood - CA',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN111-R-CA',
      barcode: '628942370670',
      market_region: 'Canada',
      description: 'Promotes Healthy Mood Balance',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Sleep - CA',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN107-R-CA',
      barcode: '628693253000',
      market_region: 'Canada',
      description: 'Sleep Aid, Calmative',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Pain Relief Topical Stick',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN108-R-UNI',
      barcode: '628693253086',
      market_region: 'Universe',
      description: 'Instantly relieves pain',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Hair Health',
      series: 'Canaherb',
      brand: 'Canaherb',
      category: 'Herbal Natural',
      SKU: 'CH-HN112-R-UNI',
      barcode: '628942370663',
      market_region: 'Universe',
      description: 'Helps to Maintain Healthy Hair',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    // NMN - Canada (CA)
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 3000 - CA',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM201-R-CA', // SKU follows best practice
      barcode: '628942007132',
      market_region: 'Canada',
      description: 'NMN 3000mg - Canada version. Stay At Your Peak.',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 6000 - CA',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM202-R-CA',
      barcode: '628942370724',
      market_region: 'Canada',
      description: 'NMN 6000mg - Canada version. Stay At Your Peak.',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 10000 - CA',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM203-R-CA',
      barcode: '628942370656',
      market_region: 'Canada',
      description: 'NMN 10000mg - Canada version. Stay At Your Peak.',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 15000 - CA',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM204-R-CA',
      barcode: '628942370687',
      market_region: 'Canada',
      description: 'NMN 15000mg - Canada version. Stay At Your Peak.',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 30000 - CA',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM205-R-CA',
      barcode: '628693253994',
      market_region: 'Canada',
      description: 'NMN 30000mg - Canada version. Stay At Your Peak.',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },

    // NMN - International (INT)
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 3000 - INT',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM201-R-INT',
      barcode: '627987829587',
      market_region: 'International',
      description: 'NMN 3000mg - International version. 成年入门养生之选',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 6000 - INT',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM202-R-INT',
      barcode: '627987829556',
      market_region: 'International',
      description: 'NMN 6000mg - International version. 成年独居慧眼之选',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 10000 - INT',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM203-R-INT',
      barcode: '627987829600',
      market_region: 'International',
      description: 'NMN 10000mg - International version. 中年远见卓识之选',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 15000 - INT',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM204-R-INT',
      barcode: '627987829570',
      market_region: 'International',
      description: 'NMN 15000mg - International version. 中年至强精英之选',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'NMN 30000 - INT',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'NMN',
      SKU: 'PG-NM205-R-INT',
      barcode: '764460916607',
      market_region: 'International',
      description: 'NMN 30000mg - International version. 中来年至臻尊荣之选',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },

    // TCM - Virility Products
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Virility - CA',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'TCM',
      SKU: 'PG-TCM301-R-CA',
      barcode: '628942007118',
      market_region: 'Canada',
      description:
        'Traditional Chinese Medicine - Virility Canada. Stay At Your Peak.',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Virility - INT',
      series: 'Phyto-Genious',
      brand: 'Phyto-Genious',
      category: 'TCM',
      SKU: 'PG-TCM301-R-INT',
      barcode: '628693253079',
      market_region: 'International',
      description:
        'Traditional Chinese Medicine - Virility International. 巅峰男士必备臻品',
      length_cm: 15.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Seal Oil - 180 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO401-R-UNI', // First SKU for 180 softgels
      barcode: '628942370700',
      market_region: 'Universe',
      description: 'Premium Seal Oil supplement for overall health support.',
      length_cm: 18.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 350.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Seal Oil - 120 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO401-S-UNI', // Second SKU for 120 softgels
      barcode: '628942370694',
      market_region: 'Universe',
      description: 'Premium Seal Oil supplement for overall health support.',
      length_cm: 18.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: activeStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'EPA 900 - 120 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO402-R-UNI',
      barcode: '628942370748',
      market_region: 'Universe',
      description:
        'High-concentration EPA 900 supplement for cardiovascular health.',
      length_cm: 18.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 350.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'EPA 900 - 60 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO402-S-UNI',
      barcode: '628719706008',
      market_region: 'Universe',
      description:
        'High-concentration EPA 900 supplement for cardiovascular health.',
      length_cm: 18.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Omega-3 900 - 120 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO403-R-UNI',
      barcode: '628942370717',
      market_region: 'Universe',
      description:
        'Omega-3 900 - Premium DHA/EPA - 180 Softgels. Omega-3 900mg softgels for brain and heart health.',
      length_cm: 18.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 350.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Omega-3 900 - 60 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO403-S-UNI',
      barcode: '628942370731',
      market_region: 'Universe',
      description:
        'Omega-3 900 - Premium DHA/EPA - 120 Softgels. Omega-3 900mg softgels for brain and heart health.',
      length_cm: 18.0,
      width_cm: 10.0,
      height_cm: 5.0,
      weight_g: 250.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'MultiVitamin Fish Oil - 120 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO404-R-UNI',
      barcode: '628719706053',
      market_region: 'Universe',
      description: 'Multivitamin-enriched fish oil for daily health support.',
      length_cm: 14.5,
      width_cm: 9.5,
      height_cm: 5.5,
      weight_g: 270.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'MultiVitamin Fish Oil - 60 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO404-S-UNI',
      barcode: '628719706060',
      market_region: 'Universe',
      description: 'Multivitamin-enriched fish oil for daily health support.',
      length_cm: 14.5,
      width_cm: 9.5,
      height_cm: 5.5,
      weight_g: 270.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Algal Oil Kids - 60 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO405-R-UNI',
      barcode: '628719706015',
      market_region: 'Universe',
      description:
        'Algal Oil specially formulated for kids’ brain and eye health.',
      length_cm: 14.5,
      width_cm: 9.5,
      height_cm: 5.5,
      weight_g: 270.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Algal Oil Kids - 30 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO405-S-UNI',
      barcode: '628719706022',
      market_region: 'Universe',
      description:
        'Algal Oil specially formulated for kids’ brain and eye health.',
      length_cm: 14.5,
      width_cm: 9.5,
      height_cm: 5.5,
      weight_g: 270.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Algal Oil Pregnant - 60 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO406-R-UNI',
      barcode: '628719706039',
      market_region: 'Universe',
      description:
        'Algal Oil DHA supplement for pregnant women and fetal development.',
      length_cm: 13.5,
      width_cm: 8.5,
      height_cm: 5.5,
      weight_g: 240.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
    {
      id: knex.raw('uuid_generate_v4()'),
      product_name: 'Algal Oil Pregnant - 30 Softgels',
      series: 'WIDE Collection',
      brand: 'WIDE Naturals',
      category: 'Marine Oil',
      SKU: 'WN-MO406-S-UNI',
      barcode: '628719706046',
      market_region: 'Universe',
      description:
        'Algal Oil DHA supplement for pregnant women and fetal development.',
      length_cm: 13.5,
      width_cm: 8.5,
      height_cm: 5.5,
      weight_g: 240.0,
      status_id: inActiveStatusId,
      status_date: knex.fn.now(),
      created_at: knex.fn.now(),
      updated_at: null,
      created_by: systemActionId,
      updated_by: null,
    },
  ];

  let successCount = 0;

  // Insert data with ON CONFLICT to avoid duplicates
  for (const product of products) {
    try {
      await knex('products')
        .insert(product)
        .onConflict('SKU') // Specify the column with the unique constraint
        .ignore(); // Ignore if the SKU already exists
      successCount++;
    } catch (error) {
      console.error('Error seeding product:', product.SKU, error.message);
    }
  }

  console.log(`${successCount} Products seeded successfully.`);
};
