const { fetchDynamicValue } = require('../03_utils');
const { generateStandardizedCode } = require('../../../utils/codeGenerators');

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  console.log('Seeding packaging_materials...');
  
  const [createdBy, activeStatusId] = await Promise.all([
    fetchDynamicValue(knex, 'users', 'email', 'system@internal.local', 'id'),
    fetchDynamicValue(knex, 'status', 'name', 'active', 'id'),
  ]);
  
  const materials = [
    // Canaherb
    {
      name: 'Plastic Flip Caps',
      color: 'white',
      grade: 'food',
      material_composition: 'plastic',
      unit: 'pcs',
      weight_g: 2,
      description: 'White food-grade plastic flip-top caps used for bottle sealing.',
    },
    {
      name: 'Vegetable Capsule 0',
      color: 'clear',
      size: '0',
      grade: 'food',
      material_composition: 'vegan',
      unit: 'pcs',
      weight_g: 0.1,
      description: 'Clear vegetarian capsule size 0',
    },
    {
      name: 'Standard Desiccant Plug',
      color: 'white',
      grade: 'food',
      material_composition: 'plastic',
      unit: 'pc',
      weight_g: 0.5,
      description: 'White desiccant packet for moisture control',
    },
    {
      name: 'Plactic Wrap Filler Single Layer',
      color: 'clear',
      grade: 'food',
      material_composition: 'plastic',
      unit: 'pc',
      weight_g: 0.5,
      description: 'Transparent food-grade plastic wrap filler for packaging cushioning.',
    },
    {
      name: '250ml Plastic Bottle',
      color: 'white',
      grade: 'food',
      material_composition: 'plastic',
      unit: 'pc',
      weight_g: 50,
      description: 'White 250ml plastic bottle for containing liquid supplements.',
    },
    {
      name: 'Pressure Seal Foam',
      color: 'white',
      grade: 'food',
      material_composition: 'foam',
      unit: 'pc',
      weight_g: 1,
      description: 'White pressure-sensitive foam seal for tamper-evident closure and moisture protection in food packaging.',
    },
    {
      name: 'Label for Focus - CA (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Focus (CA version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Focus - CN (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Focus (CN version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Gut Health - CA (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Gut Health (CA version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Gut Health - CN (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Gut Health (CN version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Immune - CA (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Immune (CA version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Immune - CN (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Immune (CN version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Memory - CA (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Memory (CA version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Memory - CN (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Memory (CN version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Menopause - CA (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Menopause (CA version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Menopause - CN (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: 'Paper label for Menopause (CN version), size 19.6×7.0cm.',
    },
    {
      name: 'Label for Mood - CA (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: '',
    },
    {
      name: 'Label for Mood - CN (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: '',
    },
    {
      name: 'Label for Sleep - CA (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: '',
    },
    {
      name: 'Label for Sleep - CN (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: '',
    },
    {
      name: 'Label for Hair Health (Paper, 19.6×7.0cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 19.6,
      width_cm: 7.0,
      description: '',
    },
    {
      name: 'Box for Focus - CA (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: 'Cardboard retail box for Focus (CA version), size 6.4×6.4×11.3cm.',
    },
    {
      name: 'Box for Focus - CN (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: 'Cardboard retail box for Focus (CN version), size 6.4×6.4×11.3cm.',
    },
    {
      name: 'Box for Gut Health - CA (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: 'Cardboard retail box for Gut Health (CA version), size 6.4×6.4×11.3cm.',
    },
    {
      name: 'Box for Gut Health - CN (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: 'Cardboard retail box for Gut Health (CN version), size 6.4×6.4×11.3cm.',
    },
    {
      name: 'Box for Immune - CA (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Immune - CN (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Memory - CA (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Memory - CN (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Menopause - CA (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Menopause - CN (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Mood - CA (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Mood - CN (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Sleep - CA (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Sleep - CN (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    {
      name: 'Box for Hair Health (Cardboard, 6.4*6.4*11.3cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.4,
      width_cm: 6.4,
      height_cm: 11.3,
      description: '',
    },
    // Phyto-Genious
    {
      name: 'Sliver Metallica Plastic Lid - Small',
      color: 'sliver',
      grade: 'food',
      material_composition: 'metallica plastic',
      unit: 'pc',
      length_cm: 1.5,
      width_cm: 1.5,
      description: 'Small silver-colored food-grade metallic plastic lid, used for sealing bottles or containers.',
    },
    {
      name: 'Copper Metallica Plastic Lid - Small',
      color: 'copper',
      grade: 'food',
      material_composition: 'metallica plastic',
      unit: 'pc',
      length_cm: 1.5,
      width_cm: 1.5,
      description: 'Small copper-colored food-grade metallic plastic lid, used for sealing bottles or containers.',
    },
    {
      name: 'Sliver Metallica Plastic Lid - Large',
      color: 'sliver',
      grade: 'food',
      material_composition: 'metallica plastic',
      unit: 'pc',
      length_cm: 1.5,
      width_cm: 1.5,
      description: 'Large silver-colored food-grade metallic plastic lid, used for sealing larger bottles or containers.',
    },
    {
      name: 'Gold Metallica Plastic Lid - Large',
      color: 'gold',
      grade: 'food',
      material_composition: 'metallica plastic',
      unit: 'pc',
      length_cm: 1.5,
      width_cm: 1.5,
      description: '',
    },
    {
      name: 'Desiccant Plastic Holder - Small',
      grade: 'food',
      material_composition: 'plastic',
      unit: 'pc',
      length_cm: 1.5,
      width_cm: 1.5,
      height_cm: 0.5,
      description: '',
    },
    {
      name: 'Desiccant Plastic Holder - Large',
      grade: 'food',
      material_composition: 'plastic',
      unit: 'pc',
      length_cm: 2.0,
      width_cm: 2.0,
      height_cm: 0.5,
      description: '',
    },
    {
      name: 'Vegetable Capsule 1',
      color: 'white',
      size: '1',
      grade: 'food',
      material_composition: 'vegan',
      unit: 'pcs',
      weight_g: 0.1,
      description: '',
    },
    {
      name: 'Plastic Wrap Filler Double Layer',
      color: 'clear',
      grade: 'food',
      material_composition: 'plastic',
      unit: 'pcs',
      weight_g: 0.1,
      description: '',
    },
    {
      name: '9k Frosted Glass Bottle',
      size: '9k',
      color: 'clear',
      grade: 'food',
      material_composition: 'frosted glass',
      unit: 'pc',
      weight_g: 220,
      description: 'Frosted glass bottle with 9k volume capacity',
    },
    {
      name: '11k Frosted Glass Bottle',
      size: '11k',
      color: 'clear',
      grade: 'food',
      material_composition: 'frosted glass',
      unit: 'pc',
      weight_g: 220,
      description: 'Frosted glass bottle with 11k volume capacity',
    },
    {
      name: 'Label for NMN 3000 - CN (Paper, 13.0*4.5cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 13.0,
      width_cm: 4.5,
      description: '',
    },
    {
      name: 'Label for NMN 3000 - CA (Paper, 13.0*4.5cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 13.0,
      width_cm: 4.5,
      description: '',
    },
    {
      name: 'Label for NMN 6000 - CN (Paper, 13.0*4.5cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 13.0,
      width_cm: 4.5,
      description: '',
    },
    {
      name: 'Label for NMN 6000 - CA (Paper, 13.0*4.5cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 13.0,
      width_cm: 4.5,
      description: '',
    },
    {
      name: 'Label for NMN 10000 - CN (Paper, 13.0*4.5cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 13.0,
      width_cm: 4.5,
      description: '',
    },
    {
      name: 'Label for NMN 10000 - CA (Paper, 13.0*4.5cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 13.0,
      width_cm: 4.5,
      description: '',
    },
    {
      name: 'Label for NMN 15000 - CN (Paper, 15.2*5.7cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 15.2,
      width_cm: 5.7,
      description: '',
    },
    {
      name: 'Label for NMN 15000 - CA (Paper, 15.2*5.7cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 15.2,
      width_cm: 5.7,
      description: '',
    },
    {
      name: 'Label for NMN 30000 - CN (Paper, 15.2*5.7cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 15.2,
      width_cm: 5.7,
      description: '',
    },
    {
      name: 'Label for NMN 30000 - CA (Paper, 15.2*5.7cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 15.2,
      width_cm: 5.7,
      description: '',
    },
    {
      name: 'Label for Virility - CN (Paper, 15.2*5.7cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 15.2,
      width_cm: 5.7,
      description: '',
    },
    {
      name: 'Label for Virility - CA (Paper, 15.2*5.7cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 15.2,
      width_cm: 5.7,
      description: '',
    },
    {
      name: 'Label for Virility - CA (Paper, 15.2*5.7cm)',
      grade: 'none',
      material_composition: 'paper',
      unit: 'm',
      length_cm: 15.2,
      width_cm: 5.7,
      description: '',
    },
    {
      name: 'Box for NMN 3000 - CN (Cardboard, 6.0*6.0*9.4cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.0,
      width_cm: 6.0,
      height_cm: 9.4,
      description: '',
    },
    {
      name: 'Box for NMN 6000 - CN (Cardboard, 6.0*6.0*9.4cm)',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.0,
      width_cm: 6.0,
      height_cm: 9.4,
      description: '',
    },
    {
      name: 'Tray Insert for Box - NMN 3000 and 6000 CN (Cardboard, 6.0×6.0×9.4cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 6.0,
      width_cm: 6.0,
      height_cm: 9.4,
      description: '',
    },
    {
      name: 'Box Lid for NMN 3000 - CA (Cardboard, 13.0×8.5×5.2cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 13.0,
      width_cm: 8.5,
      height_cm: 5.2,
      description: 'Top lid for NMN 3000 - CA packaging'
    },
    {
      name: 'Bottom Base for NMN 3000 - CA (Cardboard, 12.5×7.9×5.0cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 12.5,
      width_cm: 7.9,
      height_cm: 5.0,
      description: 'Bottom base for NMN 3000 - CA packaging'
    },
    {
      name: 'Box Lid for NMN 6000 - CA (Cardboard, 13.0×8.5×5.2cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 13.0,
      width_cm: 8.5,
      height_cm: 5.2,
      description: 'Top lid for NMN 6000 - CA packaging'
    },
    {
      name: 'Bottom Base for NMN 6000 - CA (Cardboard, 12.5×7.9×5.0cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 12.5,
      width_cm: 7.9,
      height_cm: 5.0,
      description: 'Bottom base for NMN 6000 - CA packaging'
    },
    {
      name: 'Box Lid for NMN 10000 - CA (Cardboard, 13.0×8.5×5.2cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 13.0,
      width_cm: 8.5,
      height_cm: 5.2,
      description: 'Top lid for NMN 10000 - CA packaging'
    },
    {
      name: 'Bottom Base for NMN 10000 - CA (Cardboard, 12.5×7.9×5.0cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 12.5,
      width_cm: 7.9,
      height_cm: 5.0,
      description: 'Bottom base for NMN 10000 - CA packaging'
    },
    {
      name: 'Tray Insert for NMN 3000, 6000 and 10000 - CA (Cardboard, 11.9×7.7×2.8cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 11.9,
      width_cm: 7.7,
      height_cm: 2.8,
      description: 'Tray insert for NMN 3000, 6000 and 10000 - CA packaging'
    },
    {
      name: 'Box Lid for NMN 15000 - CA (Cardboard, 13.0×8.5×5.2cm)',
      color: 'blue',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 13.0,
      width_cm: 8.5,
      height_cm: 5.2,
      description: 'Top lid for NMN 15000 - CA packaging'
    },
    {
      name: 'Tray Insert for NMN 15000 - CA (Cardboard, 11.9×7.7×2.8cm)',
      color: 'blue',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 11.9,
      width_cm: 7.7,
      height_cm: 2.8,
      description: 'Tray insert for NMN 15000 - CA packaging'
    },
    {
      name: 'Bottom Base for NMN 15000 - CA (Cardboard, 12.5×7.9×5.0cm)',
      color: 'blue',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 12.5,
      width_cm: 7.9,
      height_cm: 5.0,
      description: 'Bottom base for NMN 15000 - CA packaging'
    },
    {
      name: 'Box Lid for NMN 30000 - CA (Cardboard, 13.0×8.5×5.2cm)',
      color: 'black',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 13.0,
      width_cm: 8.5,
      height_cm: 5.2,
      description: 'Top lid for NMN 30000 - CA packaging'
    },
    {
      name: 'Tray Insert for NMN 30000 - CA (Cardboard, 11.9×7.7×2.8cm)',
      color: 'black',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 11.9,
      width_cm: 7.7,
      height_cm: 2.8,
      description: 'Tray insert for NMN 30000 - CA packaging'
    },
    {
      name: 'Bottom Base for NMN 30000 - CA (Cardboard, 12.5×7.9×5.0cm)',
      color: 'black',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 12.5,
      width_cm: 7.9,
      height_cm: 5.0,
      description: 'Bottom base for NMN 30000 - CA packaging'
    },
    {
      name: 'Box Lid for Virility - CA (Cardboard, 13.0×8.5×5.2cm)',
      color: 'darker blue',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 13.0,
      width_cm: 8.5,
      height_cm: 5.2,
      description: 'Top lid for Virility - CA packaging'
    },
    {
      name: 'Tray Insert for Virility - CA (Cardboard, 11.9×7.7×2.8cm)',
      color: 'darker blue',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 11.9,
      width_cm: 7.7,
      height_cm: 2.8,
      description: 'Tray insert for Virility - CA packaging'
    },
    {
      name: 'Bottom Base for Virility - CA (Cardboard, 12.5×7.9×5.0cm)',
      color: 'darker blue',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 12.5,
      width_cm: 7.9,
      height_cm: 5.0,
      description: 'Bottom base for Virility - CA packaging'
    },
    {
      name: 'Telescoping Box for NMN 10000 - CN (Cardboard, 8.1×8.1×12.2cm)',
      color: 'white',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 8.1,
      width_cm: 8.1,
      height_cm: 12.2,
      description: '',
    },
    {
      name: 'Telescoping Box for NMN 15000 - CN (Cardboard, 8.1×8.1×12.2cm)',
      color: 'blue',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 8.1,
      width_cm: 8.1,
      height_cm: 12.2,
      description: '',
    },
    {
      name: 'Telescoping Box for NMN 30000 - CN (Cardboard, 8.1×8.1×12.2cm)',
      color: 'black',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 8.1,
      width_cm: 8.1,
      height_cm: 12.2,
      description: '',
    },
    {
      name: 'Box for Virility - CN (Cardboard, 5.1*5.1*9.9cm)',
      color: 'darker blue',
      grade: 'none',
      material_composition: 'cardboard',
      unit: 'pc',
      length_cm: 5.1,
      width_cm: 5.1,
      height_cm: 9.9,
      description: '',
    },
    // WIDE Naturals
    {
      name: 'Aluminum Screw Cap',
      color: 'natural',
      grade: 'food',
      material_composition: 'aluminum',
      unit: 'pc',
      weight_g: 8,
      description: 'Natural color aluminum screw lid',
    },
    {
      name: 'Plastic Threaded Sealing Liner (White, 3.0×3.0cm)',
      color: 'white',
      grade: 'food',
      material_composition: 'plastic',
      unit: 'pc',
      length_cm: 3.0,
      width_cm: 3.0,
      description: 'Food-grade plastic material with threading and sealing features, used for internal sealing of bottle caps.'
    },
    {
      name: 'Softgel Capsule 500mg',
      color: 'yellow',
      size: '500mg',
      grade: 'food',
      material_composition: 'gelatin',
      unit: 'pcs',
      weight_g: 0.8,
      description: 'Standard 500mg softgel capsule',
    },
    {
      name: 'Aluminum Bottle - 220ml (White)',
      color: 'white',
      grade: 'none',
      material_composition: 'aluminum',
      unit: 'pc',
      length_cm: 3.0,
      width_cm: 3.0,
      height_cm: 12.5,
      description: '220ml white aluminum bottle for packaging'
    },
    {
      name: 'Aluminum Bottle - 440ml (White)',
      color: 'white',
      grade: 'none',
      material_composition: 'aluminum',
      unit: 'pc',
      length_cm: 3.0,
      width_cm: 3.0,
      height_cm: 16.5,
      description: '440ml white aluminum bottle for packaging'
    },
    {
      name: 'Label for Seal Oil - 120 Softgels (Plastic, 16.0*6.5cm)',
      grade: 'none',
      material_composition: 'plastic',
      unit: 'm',
      length_cm: 16.0,
      width_cm: 6.5,
      description: '',
    },
    {
      name: 'Label for Seal Oil - 180 Softgels (Plastic, 16.0*10.0cm)',
      grade: 'none',
      material_composition: 'plastic',
      unit: 'm',
      length_cm: 16.0,
      width_cm: 10.0,
      description: '',
    },
  ];
  
  const rows = materials.map((mat, idx) => ({
    id: knex.raw('uuid_generate_v4()'),
    code: generateStandardizedCode('MAT', mat.name, { sequenceNumber: idx + 1 }),
    ...mat,
    status_id: activeStatusId,
    status_date: knex.fn.now(),
    is_archived: false,
    created_by: createdBy,
    updated_by: null,
    created_at: knex.fn.now(),
    updated_at: null,
  }));
  
  await knex('packaging_materials').insert(rows).onConflict('code').ignore();
  
  console.log(`Seeded ${rows.length} packaging materials records.`);
};
